#!/bin/zsh

## end setup on fail
set -e

echo "Installing Oh My ZSH"
OVERWRITE_CONFIRMATION="no"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
echo "Oh My ZSH installed"
clear

echo "Installing Homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

if [[ "$(uname -m)" == "arm64" ]]; then
    echo "Arm64 detected, adding homebrew to path"
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
    eval "$(/opt/homebrew/bin/brew shellenv)"
    source ~/.zshrc
fi
echo "Homebrew installed and PATH configured"
echo "Installing awscli, python"
brew install --force awscli python 
brew upgrade --force awscli python 
echo "Installing firefox, sublime text, cyberduck, vscode, docker"
brew install --cask --force firefox sublime-text postman cyberduck visual-studio-code docker-desktop
clear

brew doctor

clear
# WE ARE USING NVM INSTEAD OF INSTALLING NODE THROUGH HOMEBREW BECAUSE
# 1. NODE GETS A NEW LTS VERSION EVERY YEAR
# 2. YOU DON'T HAVE TO COMPILE NODE FROM SOURCE WHEN YOUR MACOS VERSION IS UNSUPPORTED BY HOMEBREW
echo "Installing nvm"
bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash'
echo "nvm installed"
cp default-packages ~/.nvm/default-packages
echo "Installing latest node.js LTS version"
echo "yarn" >> ~/.nvm/default-packages
nvm install --lts
echo "Node.js LTS and yarn are installed"

echo "config npm to silence npm update notifier"
echo "update-notifier=false" >> ~/.npmrc
echo "npm configured"
echo "Install complete, restart your shell and/or system!"
